# Generated by Django 4.2 on 2023-06-01 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auction_category_comment_bid_auction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                default="No Categories",
                related_name="auctions",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="interested_viewers",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
