# Generated by Django 4.2 on 2023-06-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auction_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="category",
        ),
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="auctions",
                to="auctions.category",
            ),
        ),
    ]
