# Generated by Django 4.2 on 2023-06-01 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_remove_auction_category_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="auctions",
                to="auctions.category",
            ),
        ),
    ]
