# Generated by Django 4.2 on 2023-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
