# Generated by Django 4.2 on 2023-06-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_auction_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="description",
        ),
        migrations.AlterField(
            model_name="auction",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
