# Generated by Django 4.2 on 2023-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_remove_auction_description_alter_auction_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="description",
            field=models.CharField(default="testing", max_length=500),
        ),
    ]
