# Generated by Django 4.2 on 2023-06-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_auction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="description",
            field=models.CharField(max_length=1000),
        ),
    ]
