# Generated by Django 4.2 on 2023-07-26 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_user_followers_post_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="posted_time",
            new_name="timestamp",
        ),
    ]
